### PR TITLE
Add RTA Autosplitter Module

### PR DESCRIPTION
**Pull request by thearst3rd**
This is a module which does nothing but store values needed for a memory-scanning autosplitter and lays them out explicitly in memory. My [LiveSplit Autosplitter](https://github.com/thearst3rd/autosplitters/blob/main/LiveSplit.PlatinumQuest.asl) scans the "RTAAutosplitter.dll" module for the header I've defined, and from there it knows where all of the rest of the information that it needs is. Those values are populated from my RTA speedrunning mode: https://github.com/The-New-Platinum-Team/PlatinumQuest-Dev/pull/94

This code probably sucks LOL but it does work. Marking as a draft since I'm still working on it and I don't know how much I'll need to/want to change.

Demo of autosplitter: https://youtu.be/NEwpWPhl33M

Also, shoutout to @samjones246 for doing some initial legwork a while back which I could leverage here :)

### CODE REVIEW

**Comment by samjones246** [comment]
Oh hey, forgot about this! Nice job finishing it.

**Comment by RandomityGuy** [comment]
You can use a struct instead of bunch of static pointers that point within a block of memory, and it will still work in the same way.
Like this
```cpp
struct RTAAutosplitterData 
{
	char header[16];
	bool isEnabled;
	bool isDone;
	bool shouldStartRun;
	bool isPauseScreenOpen;
	S64 time;
	S64 lastSplitTime;
	S64 missionTypeBeganTime;
	S64 currentGameBeganTime;
	char* currentMission;
};
```
This struct members are aligned with the same offsets as the ones that you manually mapped the buffer with.
There is also TGE::StringTable in case you ever wanna store string references to Torque's giant string table, it is useful if the strings you are storing have already been used in the game so you just reuse the same memory, although your current approach works just a fine.
You should use StringMath::scan<bool>() since that takes care of the Torque 'true' vs '1' things and such.

**Comment by thearst3rd** [comment]
Huh, for some reason I thought that wouldn't work - I was worried that the compiler might change the memory layout of structs per compile or something. Thinking about it now, that's definitely not true because otherwise you couldn't link against an already compiled library with just the header files. Duh. I'll clean that up

**Comment by RandomityGuy** [comment]
Now that you actually have access to https://github.com/The-New-Platinum-Team/MBExtender-Dev, you should do the changes once there instead of here since this repo is somewhat outdated.

**Comment by thearst3rd** [comment]
private repo url leak😳
Yeah makes sense, I'll move it there

**Pull request closed without merging**
